declare function generateConfettiInitialFlightAngleFiredFromLeftSideOfTheScreen(): number;
declare function generateConfettiInitialFlightAngleFiredFromRightSideOfTheScreen(): number;
declare function generateConfettiInitialFlightAngleFiredFromSpecificPosition(): number;
declare function generateConfettiRotationAngleFiredFromLeftSideOfTheScreen(): number;
declare function generateConfettiRotationAngleFiredFromRightSideOfTheScreen(): number;
export { generateConfettiInitialFlightAngleFiredFromLeftSideOfTheScreen, generateConfettiInitialFlightAngleFiredFromRightSideOfTheScreen, generateConfettiInitialFlightAngleFiredFromSpecificPosition, generateConfettiRotationAngleFiredFromLeftSideOfTheScreen, generateConfettiRotationAngleFiredFromRightSideOfTheScreen, };
